# Generated by Django 4.2 on 2024-03-28 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('type', models.CharField(choices=[('default', 'Default'), ('member', 'Member'), ('blacklist', 'Blacklist')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('invite_sent', models.BooleanField(default=False)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=50)),
                ('email_template', models.TextField(default='Hi {name},\n\nYou are invited to {event_name}.\n\nYour unique QR code: {code}\n    ')),
                ('outreach_active', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('last_scanned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_scanned', to='event.attendee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='event.event'),
        ),
    ]
