# Generated by Django 4.2 on 2024-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_subject',
            field=models.CharField(default="You're Invited"),
        ),
    ]
